J1P3ter/Astraphe

common/src/main/java/com/j1p3ter/common/config/CacheConfig.java
common/src/main/java/com/j1p3ter/common/config/CorsConfigurer.java
common/src/main/java/com/j1p3ter/common/exception/ApiException.java
common/src/main/java/com/j1p3ter/common/exception/ApiExceptionHandler.java
common/src/main/java/com/j1p3ter/common/response/ApiResponse.java

- #10 
- config, exception, response 패키지 및 하위 클래스 추가
- x
-

Feat common

---

common/src/main/java/com/j1p3ter/common/exception/ApiException.java

- #10 
```java
@Getter
public class ApiException extends RuntimeException{ // Exception에서 수정
private final HttpStatus httpStatus;
private final String logMessage;
public ApiException(HttpStatus httpStatus, String errorMessage, String logMessage) {
super(errorMessage);
this.httpStatus = httpStatus;
this.logMessage = logMessage;
}
}
```
이전 : Service에서 implements ApiException을 해야 하는 상황 발생
수정 후 : implements 불필요
- 
-

fix : ApiException 타입 수정

---

astraphe-dev-setting/docker-compose.yaml
common/src/main/java/com/j1p3ter/common/auditing/AuditorAwareConfig.java
common/src/main/java/com/j1p3ter/common/auditing/AuditorAwareImpl.java
common/src/main/java/com/j1p3ter/common/auditing/BaseEntity.java
product-server/src/main/java/com/j1p3ter/productserver/application/CompanyService.java
product-server/src/main/java/com/j1p3ter/productserver/application/dto/company/CompanyUpdateRequestDto.java
product-server/src/main/java/com/j1p3ter/productserver/domain/company/Company.java
product-server/src/main/java/com/j1p3ter/productserver/domain/company/CompanyRepository.java
product-server/src/main/java/com/j1p3ter/productserver/presentation/CompanyController.java
product-server/src/test/java/com/j1p3ter/productserver/company/CompanyTest.java

- #1 
- Company RUDS
- Auditor Long 타입으로 변경
- docker-compose 실행 순서 추가(zookeeper -> kafka -> kafka-ui)
- 
-

Company RUDS & Test Code 작성, Auditor Long 타입으로 변경, docker-compose 수정

---

build.gradle
gateway/build.gradle
gateway/src/main/java/com/j1p3ter/gateway/GatewayApplication.java
gateway/src/main/java/com/j1p3ter/gateway/infrastructure/jwt/JwtAuthorizationFilter.java
gateway/src/main/resources/application-dev.yaml
gateway/src/main/resources/application.yaml

- #21 
- commit message에 있는 issue tracking number가 8이라고 되어 있는데 21이 맞습니다.
- 불필요한 코드를 제거하고 있습니다.
- x
-

Refactor gateway 8

---

common/src/main/java/com/j1p3ter/common/auditing/BaseEntity.java
common/src/main/java/com/j1p3ter/common/config/global/CorsConfigurer.java
common/src/main/java/com/j1p3ter/common/config/redis/CacheConfig.java

- #10 
- server host, port 등의 값 @value annotation 적용
- base entity isdelete -> isdeleted 변경
- 
-

Common Module 수정

---

gateway/src/main/java/com/j1p3ter/gateway/infrastructure/config/GatewayConfig.java

- #24 
- 대기열 서버 라우팅 비활성화
- 향후 구현 예정
- x
-

refactor: inactivate queue-server routing (#24)

---

user-server/src/main/java/com/j1p3ter/userserver/application/dto/LogInResponseDto.java
user-server/src/main/java/com/j1p3ter/userserver/application/dto/UserDeleteResponseDto.java
user-server/src/main/java/com/j1p3ter/userserver/application/dto/UserGetResponseDto.java
user-server/src/main/java/com/j1p3ter/userserver/application/dto/UserUpdateResponseDto.java
user-server/src/main/java/com/j1p3ter/userserver/application/service/UserService.java
user-server/src/main/java/com/j1p3ter/userserver/domain/exception/IdentityVerificationFailedException.java
user-server/src/main/java/com/j1p3ter/userserver/domain/exception/LoginIdDuplicatedException.java
user-server/src/main/java/com/j1p3ter/userserver/domain/exception/PasswordNotMatchesException.java
user-server/src/main/java/com/j1p3ter/userserver/domain/model/User.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/controller/AuthController.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/controller/UserController.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/request/SignUpRequestDto.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/request/UserUpdateRequestDto.java
user-server/src/main/resources/application.yaml
user-server/src/test/java/com/j1p3ter/userserver/application/unittest/AuthServiceTest.java

- #2
- 회원 가입 try-catch 수정
- UserController 추가
- 사용자 조회, 수정, 삭제 API 추가
- 회원가입 테스트 코드 추가
- 
-

Feat user 2

---

gateway/src/main/java/com/j1p3ter/gateway/GatewayApplication.java
gateway/src/main/java/com/j1p3ter/gateway/infrastructure/config/GatewayConfig.java
gateway/src/main/java/com/j1p3ter/gateway/infrastructure/jwt/JwtAuthorizationFilter.java
gateway/src/main/java/com/j1p3ter/gateway/presentation/exception/GatewayExceptionHandler.java
gateway/src/main/resources/application.yaml
user-server/src/main/java/com/j1p3ter/userserver/infrastructure/configuration/SecurityConfig.java
user-server/src/main/java/com/j1p3ter/userserver/infrastructure/configuration/SwaggerConfig.java
user-server/src/main/java/com/j1p3ter/userserver/infrastructure/jwt/JwtUtil.java

- #24 
- user-server에 swagger-ui 설정 클래스를 추가하여 gateway의 클러스터링이 동작하지 않던 문제를 수정
- 라우팅 및 필터링을 거치는 api 경로 추가
- JwtAuthorizationFilter.filter()에서 다음 필터로 요청을 전달하는 `return chain.filter(exchange);` 추가
- user-server, product-server 쪽에서 postman을 이용하여 API test 진행 - 성공
-

Fix gateway (#24)

---

user-server/src/test/java/com/j1p3ter/userserver/application/unittest/AuthServiceTest.java

- #2
- 회원 가입 테스트를 성공과 실패의 경우로 분리
- 성공
-

Feat: add test codes (#2)

---

order-server/src/main/java/com/j1p3ter/orderserver/domain/order/Order.java
order-server/src/main/java/com/j1p3ter/orderserver/domain/order/OrderDetail.java

#5
- 
is_delete > is_deleted로 변 경 
- 
- 
-

fix_order_#5

---

user-server/src/main/java/com/j1p3ter/userserver/application/service/UserService.java
user-server/src/main/java/com/j1p3ter/userserver/domain/model/User.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/request/LogInRequestDto.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/request/UserUpdateRequestDto.java
user-server/src/main/resources/application-dev.yaml
user-server/src/test/java/com/j1p3ter/userserver/application/integrationtest/UserServiceTest.java

- #2 
- 테스트 코드 추가
- RequestDto에 생성자 추가
- delete 버그 수정: @SqlDelete에서 id를 user_id로 변경
-

User Server 테스트 코드 추가 및 delete 버그 수정

---

common/src/main/java/com/j1p3ter/common/auditing/AuditorAwareImpl.java
product-server/build.gradle
product-server/src/main/java/com/j1p3ter/productserver/application/ProductService.java
product-server/src/main/java/com/j1p3ter/productserver/domain/product/Product.java
product-server/src/main/java/com/j1p3ter/productserver/infrastructure/kafka/EventSerializer.java
product-server/src/main/java/com/j1p3ter/productserver/infrastructure/kafka/event/ReduceStockEvent.java
product-server/src/main/java/com/j1p3ter/productserver/infrastructure/kafka/handler/KafkaErrorHandler.java
product-server/src/main/java/com/j1p3ter/productserver/infrastructure/kafka/messaging/ProductEventConsumer.java
product-server/src/main/java/com/j1p3ter/productserver/presentation/KafkaTestController.java
product-server/src/main/java/com/j1p3ter/productserver/presentation/ProductController.java
product-server/src/main/resources/application-dev.yaml
product-server/src/main/resources/application-prod.yaml
product-server/src/main/resources/application.yaml

- #28
- Product Server Kafka 설정
- Reduce Stock Kafka 로직 구현
- AuditorAwareImpl 수정 - kafka 사용을 위해 수정
- kafka topic 추가 확인
- 테스트용 Controller 추가
-

Reduce Stock Kafka 로직 구현

---

user-server/src/main/java/com/j1p3ter/userserver/application/service/UserService.java
user-server/src/test/java/com/j1p3ter/userserver/application/integrationtest/UserServiceTest.java

- #2
- softDelete 적용
- test code 수정
- 성공
-

fix: use softDelete (#2)

---

gateway/src/main/java/com/j1p3ter/gateway/infrastructure/config/GatewayConfig.java
gateway/src/main/java/com/j1p3ter/gateway/infrastructure/jwt/JwtAuthorizationFilter.java
user-server/src/main/java/com/j1p3ter/userserver/application/dto/SignUpResponseDto.java
user-server/src/main/java/com/j1p3ter/userserver/application/dto/UserGetResponseDto.java
user-server/src/main/java/com/j1p3ter/userserver/application/dto/UserUpdateResponseDto.java
user-server/src/main/java/com/j1p3ter/userserver/application/service/UserService.java
user-server/src/main/java/com/j1p3ter/userserver/domain/model/User.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/request/SignUpRequestDto.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/request/UserUpdateRequestDto.java
user-server/src/test/java/com/j1p3ter/userserver/application/integrationtest/UserServiceTest.java
user-server/src/test/java/com/j1p3ter/userserver/application/unittest/AuthServiceTest.java

- #37 
- User Entity에 shippingAddress 필드 추가
- Gateway에서 /api/shipping-addresses/** 라우팅 제거
-

Feat shipping address 37

---

product-server/build.gradle
product-server/src/main/java/com/j1p3ter/productserver/ProductServerApplication.java

- #44 
- Product Server FeignClient 사용 설정
- X
-

feat: Product Server FeignClient 사용 설정 (#44)

---

astraphe-dev-setting/prometheus.yml
eureka-server/src/main/resources/application.yaml
gateway/src/main/resources/application.yaml
order-server/src/main/resources/application.yml
product-server/src/main/resources/application.yaml
user-server/src/main/resources/application.yaml

-  #40 
-  prometheus 사용 설정
- 
-

Feat monitoring 40

---

.github/workflows/dockerHubCiCd.yaml
Dockerfile
docker-compose.yaml
gateway/src/main/java/com/j1p3ter/gateway/GatewayApplication.java
gateway/src/main/resources/application-dev.yaml
gateway/src/main/resources/application-prod.yaml
user-server/src/main/resources/application-prod.yaml

- #39 
- CI/CD pipelines 추가
- Gateway Redis 설정 제거
- User Server redis env vars 적용
- x
-

Feat cicd 39

---

gateway/src/main/java/com/j1p3ter/gateway/infrastructure/config/GatewayConfig.java
gateway/src/main/java/com/j1p3ter/gateway/infrastructure/jwt/JwtAuthorizationFilter.java
user-server/src/main/resources/application-dev.yaml
user-server/src/main/resources/application.yaml

- #24 
- 대기열 서버 라우팅 추가
- 사용자 서버 application**.yaml 변수 최적화
- x
-

Refactor gateway 24

---

common/build.gradle

- #49 
- bootJar enabled=false 추가
- 
-

hotfix: add bootJar enabled=false

---

.github/workflows/dockerHubCiCd.yaml
docker-compose.yaml
gateway/src/main/resources/application.yaml
queue-server/src/main/resources/application-dev.yaml
queue-server/src/main/resources/application-prod.yaml
queue-server/src/main/resources/application.yml
user-server/src/main/resources/application-prod.yaml
user-server/src/main/resources/application.yaml

- None
- change deploy scripts
- 
-

hotfix: change deploy in cicd pipeline

---

docker-compose.yaml

- #39
- networks 위에 있는 '-' 제거
- x
-

hotfix: change docker-compose.yaml

---

queue-server/build.gradle
queue-server/src/main/java/com/j1p3ter/queueserver/application/client/ProductClient.java
queue-server/src/main/java/com/j1p3ter/queueserver/application/dto/ProductOptionDto.java
queue-server/src/main/java/com/j1p3ter/queueserver/application/dto/ProductResponseDto.java
queue-server/src/main/java/com/j1p3ter/queueserver/presentation/controller/QueueController.java

- #12 
-  dto 의존성 제거 / queue 내에 생성
- 
-

!HOTFIX : productDto 의존성 제거 (#12)

---

user-server/src/main/java/com/j1p3ter/userserver/UserServerApplication.java

- #39 
- UserServerApplication의 scanBasePackages에 common 패키지 추가
- 
-

hotfix: scan common module packages

---

user-server/src/main/resources/application-prod.yaml

fix: User-server DEBUG_MODE 추가 (#39)

---

.github/workflows/dockerHubCiCd.yaml

fix: docker compose build no cache 설정 (#39)

---

.github/workflows/dockerHubCiCd.yaml

Merge into main

---

common/src/main/java/com/j1p3ter/common/config/redis/CacheConfig.java
user-server/src/main/java/com/j1p3ter/userserver/UserServerApplication.java
user-server/src/main/java/com/j1p3ter/userserver/application/dto/UserGetResponseDto.java
user-server/src/main/java/com/j1p3ter/userserver/application/service/UserService.java
user-server/src/main/java/com/j1p3ter/userserver/infrastructure/configuration/RedisConfig.java

- #2
- 사용자 조회 Caching 기능 추가
- 
-

feat: cache user

---

product-server/src/main/java/com/j1p3ter/productserver/application/CompanyService.java
product-server/src/main/java/com/j1p3ter/productserver/application/dto/company/CompanyCreateRequestDto.java
product-server/src/main/java/com/j1p3ter/productserver/presentation/CompanyController.java

- #72 
- Company Create시 userId Body로 받던 부분 수정
- Update, Delete Transaction Exception 처리 추가
- Swagger 결과 화면
-

Fix company 72

---

common/src/main/java/com/j1p3ter/common/exception/ApiExceptionHandler.java
product-server/src/main/java/com/j1p3ter/productserver/application/ProductService.java
product-server/src/main/java/com/j1p3ter/productserver/application/dto/DirectionType.java
product-server/src/main/java/com/j1p3ter/productserver/application/dto/SortType.java
product-server/src/main/java/com/j1p3ter/productserver/domain/product/ProductCustomRepositoryImpl.java
product-server/src/main/java/com/j1p3ter/productserver/presentation/ProductController.java

- #74 
- Product Transaction Exception 처리
- Sort, Direction 관련해서 잘못된 값 들어올 경우 400 error 반환
- MethodArgumentTypeMismatchException Handler 추가
- 원가보다 할인가가 높은 경우 에러 반환하게 로직 수정
- 잘못된 값 400
- 할인가가 높은 경우
-

Fix product 74

---

user-server/src/main/java/com/j1p3ter/userserver/infrastructure/configuration/BindingResultAop.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/controller/AuthController.java

- #77 
- User server에 @Valid 예외 처리를 수행하는 AOP 추가
- 
-

feat: add AOP

---

user-server/src/main/java/com/j1p3ter/userserver/infrastructure/configuration/BindingResultAop.java

- #77 
- BAD_GATEWAY -> BAD_REQUEST 수정
- 
-

fix: change from BAD_GATEWAY to BAD_REQUEST

---

gateway/src/main/java/com/j1p3ter/gateway/infrastructure/jwt/JwtAuthorizationFilter.java
user-server/build.gradle
user-server/src/main/java/com/j1p3ter/userserver/application/service/UserService.java
user-server/src/main/java/com/j1p3ter/userserver/domain/repository/UserRepository.java
user-server/src/main/java/com/j1p3ter/userserver/infrastructure/configuration/QueryDslConfig.java
user-server/src/main/java/com/j1p3ter/userserver/infrastructure/configuration/QueryDslUtil.java
user-server/src/main/java/com/j1p3ter/userserver/infrastructure/repository/QueryDslUserRepository.java
user-server/src/main/java/com/j1p3ter/userserver/infrastructure/repository/QueryDslUserRepositoryImpl.java
user-server/src/main/java/com/j1p3ter/userserver/presentation/controller/UserController.java

- #80 
- GET /api/users 추가
- Gateway 인가 설정 추가
- QueryDsl 설정 추가
- Redis 캐싱 기능 수정
-

feat: add GET '/api/users'

---

README.md

docs: add API document
